[[redirects]]
  from = "/api/platform/*"
  to = "/api/platform/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "http://13.51.36.92/api/:splat"
  status = 200
  force = true
